version: 0.2

            
phases:
  build:
    commands:
      - rm -rf config
      - rm -rf external-resources/product
      - git config --global credential.helper "!aws codecommit credential-helper $@"
      - git config --global credential.UseHttpPath true
      - git clone https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/cattleya_test000 config --depth 1
      - mv config/product external-resouces/product
      - rm -rf config
      - mvn package

  post_build:
    commands:
      - export DIRECTORY=`date +%Y/%m%d`
      - mkdir `date +%Y/%m%d` -p
      - mv target/*.jar `date +%Y/%m%d`
      - mv target/*.jar .
artifacts:
  files:
    - $DIRECTORY/excelconverter-1.0.jar
    - target/excelconverter-1.0.jar

