version: 0.2

            
phases:
  build:
    commands:
      - rm -rf config
      - rm -rf external-resources/product
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git clone https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/cattleya_test000 config --depth 1
      - mv config/product external-resources/product
      - rm -rf config
      - bash build/$ENV.sh

  post_build:
    commands:
      - export DIRECTORY=`date +%Y/%m/%d`
      - export TIMESTAMP=`date +%Y%m%d%H%M%S`
      - cp target/excelconverter-1.0.jar excelconverter-1.0.jar
      - aws s3 cp excelconverter-1.0.jar s3://shiromakenji-first-test/$ENV/latest/excelconverter-1.0.jar
      - aws s3 cp excelconverter-1.0.jar s3://shiromakenji-first-test/$ENV/$DIRECTORY/excelconverter-$TIMESTAMP.jar
