version: 0.2

            
phases:
  build:
    commands:
      - mvn package

  post_build:
    commands:
      - mkdir `date +%Y`/`date +%m`/`date +%d`
      - mv target/*.jar 
artifacts:
  files:
    - *.jar
  discard-paths: yes
#  base-directory: location
